// <auto-generated />
namespace VRASearchEngine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Converted_TPH_TPT_Added_Admin_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Converted_TPH_TPT_Added_Admin_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202510181335560_Converted_TPH_TPT_Added_Admin_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
